name: test

on:
  - push
  - pull_request

jobs:
  test:
    name: ${{ github.event_name }} test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo '${{ github.event_name }}'
